name: "Build @react-cad/core"
description: "Build the core wasm library in local docker"
runs:
  using: "docker"
  image: "../../../packages/core/Dockerfile"
  entrypoint: /github/workspace/packages/core/build.sh
  args:
    - -b
    - /github/workspace/packages/core/build
    - -s
    - /github/workspace/packages/core/src
    - -d
    - /github/workspace/packages/core
    - -f
    - ci
