name: 'Build @react-cad/core'
description: 'Build the core wasm library in docker'
runs:
  using: 'docker'
  image: 'reactcad/build:7.5.0-v2'
  entrypoint: /github/workspace/packages/core/build.sh
  args:
    - -b
    - /github/workspace/packages/core/build
    - -s
    - /github/workspace/packages/core/src
    - -d
    - /github/workspace/packages/core
    - -f
    - ci
