name: "Build @react-cad/core"
description: "Build the core wasm library in docker"
inputs:
  tag:
    description: "Which docker image version to use"
    default: "latest"
runs:
  using: "docker"
  image: ${{ format('reactcad/build:{0}', inputs.tag) }}
  entrypoint: /github/workspace/packages/core/build.sh
  args:
    - -b
    - /github/workspace/packages/core/build
    - -s
    - /github/workspace/packages/core/src
    - -d
    - /github/workspace/packages/core
    - -f
    - ci
