name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: reactcad/build
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./packages/core
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=reactcad/build:latest
          cache-to: type=inline
  npm:
    name: Publish to NPM
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install
      - name: Update docker action
        run: 'sed -i "s/latest/${{ github.ref_name }}/" .github/actions/build-core/action.yml'
      - name: Build core wasm
        uses: ./.github/actions/build-core
      - name: Revert docker action
        run: git restore .github/actions/build-core/action.yml
      - name: Build Typescript
        run: yarn nps build.ts
      - name: Release
        run: yarn lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          repository-name: react-cad/react-cad.github.io
          branch: main
          folder: packages/docs/storybook-static
          git-config-name: "React CAD Bot"
          git-config-email: "react.cad.dev+bot@gmail.com"
          tag: ${{github.ref_name}}
