name: Lint & Test

on:
  pull_request:
    branches:
      - main

jobs:
  dockerfile:
    name: Check Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Dockerfile for changes
        run: packages/core/dockerfile-changed.sh
  test-local:
    name: "Lint & Test (local docker)"
    needs: dockerfile
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build core wasm
        uses: ./.github/actions/build-core-local
      - name: Build Typescript
        run: yarn nps build.ts
      - name: Test
        run: yarn test
  test-latest:
    name: "Lint & Test (latest docker)"
    needs: dockerfile
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build core wasm
        uses: ./.github/actions/build-core
      - name: Build Typescript
        run: yarn nps build.ts
      - name: Test
        run: yarn test
