name: Lint & Test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: "Build docker image"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.dockerfile.outputs.changed }}
      tag: ${{ steps.dockerfile.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Dockerfile
        id: dockerfile
        uses: ./.github/actions/check-dockerfile
      - name: Set up Docker Buildx
        if: ${{ steps.dockerfile.outputs.changed == 'true' }}
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ steps.dockerfile.outputs.changed == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ steps.dockerfile.outputs.changed == 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: ./packages/core
          push: true
          tags: "reactcad/build:pr-${{ github.event.number }}"
          cache-from: "type=registry,ref=reactcad/build:pr-${{ github.event.number }}"
          cache-to: type=inline
  test:
    name: "Lint & Test"
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Update docker action (pr)
        if: ${{ needs.docker.outputs.changed == 'true' }}
        run: 'sed -i "s/latest/pr-${{ github.event.number }}/" .github/actions/build-core/action.yml'
      - name: Update docker action (tag)
        if: ${{ needs.docker.outputs.changed == 'false' }}
        run: 'sed -i "s/latest/${{ needs.docker.outputs.tag }}/" .github/actions/build-core/action.yml'
      - name: Build core wasm
        uses: ./.github/actions/build-core
      - name: Build Typescript
        run: yarn nps build.ts
      - name: Test
        run: yarn test
